### ISSUE TITLE
Study activity similar to Anki and a settings or about page.

### ISSUE THREAD

**Issue by dkanada** [blastrock/kakugo#1]
Not sure if you have used Anki in the past, but basically it shows you one kanji or word, and then after you hit the show button it displays the kana, meaning, example sentences, and other included information. It also lets you select how well you knew the word manually so the SRS would still be applicable. This would be nice because sometimes I like to view as much information as possible about a kanji. I still haven't figured out the best way to integrate this into your app, but it looks like all of the information for a given item is visible in the backend so it wouldn't be too hard to find a layout to make this work.

I would also enjoy a settings page, mainly to add a dark theme. The quiz filters might work better in the settings or perhaps with a filter icon on the toolbar in the individual activities rather than in the main content section. Would you be open to pull requests?

**Comment by blastrock** [comment]
I consider that this is done, I am closing this.
