### ISSUE TITLE
Add kana writing activity

### ISSUE THREAD

**Issue by btp** [blastrock/kakugo#10]
I'm very much enjoying using your app. Thank you!

I thought it might be easy to add hiragana and katakana writing activities similar to the kanji quiz (#2), because [KanjiVG](https://kanjivg.tagaini.net/) includes the kana.

Thank you again for creating this app!

**Comment by blastrock** [comment]
Thanks for the issue and the PR. The kakugo database doesn't contain the hiragana and katakana strokes yet, I will add them and complete the feature.

Thank you for your support!

**Comment by btp** [comment]
Aha, thanks for your response!

I've just had a look at the database structure. So, would you need to move the kana from `data/Kanas.kt` to the `kanjis`, `kanjis_similars`, and `strokes` tables in the database, with ids starting sequentially after 2792 (currently the last entry in the`kanjis` table) so as not to interfere with the existing kanji? I was expecting unicode codepoints somewhere, but maybe that would have complicated matters?

**Comment by blastrock** [comment]
IDs don't really mean anything actually, they are just there for lookup. I should probably use code points as you suggest, that was a bad design decision.

I have a script that rebuilds the database from the multiple dictionaries, I need to change it from there and put the kanas there too. I haven't opensourced it as it is very very ugly ^^

**Comment by btp** [comment]
> I have a script that rebuilds the database from the multiple dictionaries, [...] I haven't opensourced it as it is very very ugly ^^

Ha! Fair enough. I thought I could do some of the tedium work for you, but it looks as if you've got it covered. Maybe I'll keep poking at it and see what I can come up with.

Cheers

**Comment by blastrock** [comment]
Released in 1.21.2

**Comment by btp** [comment]
Thank you for completing this!

It works wonderfully for the hiragana, but there's something wrong with the katakana writing test: the hints don't work, and correct strokes are never recognized.

**Comment by blastrock** [comment]
Yes, it should be fixed in 1.21.3.

**Comment by btp** [comment]
Aha, yes, it's fixed in 1.21.3. Apologies for the hasty comment. And thank you again for adding this feature! I really need practice on writing the katakana.
