### ISSUE TITLE
Add Setting to Disable Flashy Animations

### ISSUE THREAD

**Issue by OVERPWREDCATSCIENCE** [blastrock/kakugo#14]
First off, thank you for developing Kakugo. Can an option be added to the settings menu to remove the animation displayed after selecting an answer? I personally find the animation distracting.

**Comment by longus-catus** [comment]
I agree!  I have found the addition of the animations gratuitous. And would like an option to disable them.

**Comment by blastrock** [comment]
I have put these animation because the application lacked feedback when you get something wrong, the only way to see it was to look at the bottom of the screen. I think this feedback is necessary, and instead of adding an option to disable the animation, I'd rather improve it, or replace it by something else.

Can you elaborate on why you don't like it? Is it the animation itself? Is it just that the colors are too flashy? Is it about both correct and wrong animations?

**Comment by longus-catus** [comment]
> I have put these animation because the application lacked feedback when you get something wrong, the only way to see it was to look at the bottom of the screen. I think this feedback is necessary, and instead of adding an option to disable the animation, I'd rather improve it, or replace it by something else.
> 
> Can you elaborate on why you don't like it? Is it the animation itself? Is it just that the colors are too flashy? Is it about both correct and wrong animations?

The worst part is that they take time...even a few hundred milliseconds is annoying when it's stolen from you...  It wasn't like that before, and it's like that now, so it feels like it's been stolen.

There is already feedback at the bottom: red or green.

**Comment by OVERPWREDCATSCIENCE** [comment]
After using the app a little more I have gotten used to the animations, and I am beginning to understand the reasoning behind the animations. 
That being said I have come up with some potential replacements:
- Make the background change color, green for correct and red for incorrect.
- Make a check mark appear (or a circle as it is used in Japan) if an answer is correct and a red "X" if the answer is wrong.
- Alternatively, when an answer is wrong you could have the correct character appear, either appear in the center of the screen, or a dialog box informing the user of the correct answer.

**Comment by blastrock** [comment]
Thanks for all the feedback! I don't have much time to work on kakugo lately, but I will definitely do something for this :)

**Comment by blastrock** [comment]
I started to work on this but couldn't finish yet, so the new version still has the issue, but I haven't forgotten about it :) 

> I don't want to study outside of the framework the learning tool I'm using (RTKv6 in this case).

RTKv6 classification is now available on kakugo!

**Comment by longus-catus** [comment]
> RTKv6 classification is now available on kakugo!

This is much appreciated...it has such a familiar feel now.  

I did notice an issue where each group contains one more kanji (201) than it should (200) and therefore overlaps with the first one of the following group.  Selecting or deselecting one affects the other group.

**Comment by blastrock** [comment]
Oops, how could I miss that... Will be fixed in the next version :)

**Comment by blastrock** [comment]
Flashy animations have been removed in 1.24.
