### ISSUE TITLE
Documentation for kanji import function

### ISSUE THREAD

**Issue by longus-catus** [blastrock/kakugo#15]
I rethought this request, and at the core it is simply a request for documentation on the kanji list import.  I incorrectly asked about kanji words.

To answer about the AnkiDroid format, it is a sqlite database with same schema as Anki.  It's described at https://github.com/ankidroid/Anki-Android/wiki/Database-Structure, and a plugin I think might be useful in understanding how kakugo could extract data useful for it is https://github.com/tsudoko/kanjigrid.

As for its usefulness, it would support any order for learning kanji...but that can be better understood as simply a request for adding support for the heisig6 index, which already exists in the KANJIDIC file.  

It's substantially different from the JLPT ordering because it's part of a learning system based on the official radical system supplemented with the author's additional creations.  There are a couple other systems like it, but it's definitely the most talked about system that isn't frequency-based or JLPT-based.  I can create another issue for this request.

**Comment by blastrock** [comment]
Word lists can't be saved at the moment.

And about importing kanji list, I am not sure what you are talking about. I use a generic intent for that, it should open *your* file picker.

I should indeed add something about the file format to be imported.

I don't know what is the ankidroid format. Sorry for this one, but I don't think I will invest time on that unless there is more demand.

**Comment by longus-catus** [comment]
Thank you.  The save/load does work as intended, although not as I originally expected.  I expected save/load to also export/import, and under that assumption certain things seem wrong that actually aren't wrong.  

I updated the original request to include a better description of what I wanted regarding documentation, and my comment about AnkiDroid and what I meant by it.

**Comment by blastrock** [comment]
I have added a message box explaining the format for the file to be imported when importing a kanji selection.

Also, kakugo can now sort kanji by Remember The Kanji index, I forgot to ping you when I released it :)
