### ISSUE TITLE
Option to practice drawing on incorrect answer

### ISSUE THREAD

**Issue by TiloWiklund** [blastrock/kakugo#17]
It would be nice to have the option to practice drawing kanji/kana after having the correct one revealed upon giving up with "don't know". Something like having the correct kanji/kana show up grayed out and forcing you to fill in the strokes in the correct order.

I found this quite useful in vocabulary training applications like lingvist.

**Comment by blastrock** [comment]
Good idea, I think this would be cool, I'll work on it :)
