### ISSUE TITLE
Donating to the project.

### ISSUE THREAD

**Issue by mbfraga** [blastrock/kakugo#22]
Hello,
I was simply wondering if there is a way to donate to the project. I am already planning to donate upstream, but would be happy to donate to Kakugo directly as well. I don't really have time to donate my time at this point. 

I found it via f-droid after buying kanjistudy, and I am so happy there is an FOSS version available! (specially since the aforementioned uses mostly OSS libraries)

At any rate, it's good to have this question answered and documented, so this ticket would help with that :P

**Comment by blastrock** [comment]
Wow, I didn't think there would be people wanting to donate, well thank you :)

I will set up a paypal or something and put a link in the readme probably.

**Comment by firstbass** [comment]
Seconded. This has been amazing. It has helped me learn the kana and is proving wonderful with the Kanji. I would love to be able to pay you for your efforts in putting all this together.

**Comment by blastrock** [comment]
I really didn't expect such enthusiasm, thank you, it means a lot to me :)

I've put a donation section in the [readme](https://github.com/blastrock/kakugo/blob/master/README.rst#donations) with a paypal link and a bitcoin address (because I want to be part of the cool kids).
