### ISSUE TITLE
Accidental pressing of "Next" in Drawing Kanji

### ISSUE THREAD

**Issue by mbfraga** [blastrock/kakugo#23]
**Issue:** In "Kanji Drawing", it is not unusual that after I finish drawing a Kanji, and I accidentally double tap on "Next". Often, this will cause me to hit "Don't Know" on the next Kanji. 

I use the drawing feature a lot and am quite fast with it, which is part of why I will have these "misclicks".

**Possible Solutions:** Rearrange buttons, or add an alternative way of going to the next kanji.

**Comment by blastrock** [comment]
Thanks for the issue! It doesn't happen to me on Kakugo, but I know I hate it when it happens on the Internet or other apps, so I'll do something. I think I will just disable the buttons for half a second after a new question has appeared.
