### ISSUE TITLE
In "X to romaji writing", autofill service kicks in

### ISSUE THREAD

**Issue by logic** [blastrock/kakugo#32]
I use Bitwarden as my password manager, which uses Android's autofill service to trigger on username/password fields in a given application (I imagine 1Password, LastPass, and others would have a similar issue, since the autofill service is what's triggering the action). In "hiragana/katakana to romaji writing", which pops up a text entry field, the autofill service triggers, thinking it's either a username or password entry field.

It looks like you might just need to set `android:importantForAutofill="no"` on the TextView to make it stop? https://developer.android.com/guide/topics/text/autofill-optimize#important

**Comment by blastrock** [comment]
Thanks for the bug report and the suggestion. I just released the 1.30.1 beta on the play store with that fix, if there is no issue I will release it as stable. I can't really test the fix myself, my password manager is not triggered by Kakugo, so if you can give it a try it would be nice :)

**Comment by logic** [comment]
1.30.1 seems to have fixed it, thank you!
