### ISSUE TITLE
Add an option to hide the answers initially

### ISSUE THREAD

**Issue by vesatoivonen** [blastrock/kakugo#5]
Learning progress seems to improve when instead of picking the most correct one from the choices shown, retrieval from memory alone is tried first.
To avoid even glancing the available answer choices I'd suggest to implement a feature which would allow to toggle answers' visibility on the quiz view.
This would like #2, but a bit easier to implement.

**Comment by blastrock** [comment]
Sorry, I am only seeing this now as github didn't send me any notification.

I agree with you. When I am doing the quizzes, I force myself to answer the question *without* looking at the answers, and if I don't know the answer, I press "don't know" even if seeing the answers made me remember the answer.

I can add that option, but having tried it, it didn't work for me. I usually answer to questions fast, and I got used to clicking on "show the answers" before I am sure I have the answer, as a reflex. So the button was useless for me. But maybe it's different for other people, I can add that option.

**Comment by blastrock** [comment]
This is now done
