### ISSUE TITLE
Plans for UI translations

### ISSUE THREAD

**Issue by Wilker-a** [blastrock/kakugo#50]
what are your plans for translating this program to languages other than english?

i want to help translating it to portuguese (pt-br) and it would be nice to have it listed on [Weblate](https://hosted.weblate.org/) =^-^=

**Comment by blastrock** [comment]
There are no plans on translating the application, but pull requests are welcome. The major issue is that even if the app is translated, the dictionaries aren't.

**Comment by Wilker-a** [comment]
aww :( 

is there any way to make an edit of the dictionary though?

**Comment by blastrock** [comment]
The dictionaries are managed by Jim Breen. He says that he handles contributions manually here: https://www.edrdg.org/wiki/index.php/KANJIDIC_Project#Proposing_Changes , you would have to send them to him.

**Comment by Wilker-a** [comment]
i see. thank you \^\^

**Comment by blastrock** [comment]
I have given more details in #7, I don't plan to support more translations unless the dictionaries themselves are translated.
