### ISSUE TITLE
Translate Kakugo in other languages

### ISSUE THREAD

**Issue by lnjX** [blastrock/kakugo#7]
I'd like to translate the vocabulary to German. 

Providing translations to other languages makes it much easier to learn Kanji/vocabulary as a non-native English speaker.

**Comment by blastrock** [comment]
Let me update this. Kakugo is based on [kanjidic](https://www.edrdg.org/wiki/index.php/KANJIDIC_Project) and [JMdict](https://www.edrdg.org/jmdict/edict_doc.html). I do not plan on supporting translations of Kakugo if the dictionaries are not translated in those languages as I think it's the most important part of Kakugo.

Currently the only languages available in kanjidic are English, French, Spanish and Portuguese.
JMdict offers more translations, but Portuguese is not one of them.

Which means that Kakugo currently supports English, French and Spanish and can't support more languages unless more translations are done in the above projects.

Note that Kakugo features only the 2500 most used kanji (where the `<freq>` tag is present in kanjidic2) and the words that were in _"Ichimango goi bunruishuu", Senmon Kyouiku Publishing, Tokyo, 1998_ (where the `ichi1` tag is present in the JMdict), which represents ~13k words.

**Comment by obfusk** [comment]
> I do not plan on supporting translations of Kakugo if the dictionaries are not translated in those languages as I think it's the most important part of Kakugo.

I think that combining e.g. the German JMDict with the English Kanjidic could still be more useful for German speakers than only having a completely English version. Same for Dutch and other languages that have decent JMDict data. Especially since kanji "meanings" are IMHO much less important to get "exact" than vocabulary.
