### ISSUE TITLE
Custom fonts don't work

### ISSUE THREAD

**Issue by mheiken** [blastrock/kakugo#79]
I don't like to learn kanji with the default sans serif font, so I was glad to find that there is a custom font setting. But after enabling the option and selecting the .ttf font file, there were no errors but all kanji and kana are still in the default font.
I use Kakugo v. 1.36.1 (in German if that matters) from F-Droid on MIUI Global 12.5.2.
I tried seven different .ttf font files, among them Kanji stroke order font v4.004 or AC Kaisho. They work in AnkiDriod.

**Comment by blastrock** [comment]
Thanks for the bug report. Android chose to break app features silently once again, it took me hours to find this one ><

Anyway, the bug is fixed in 1.36.2, the release is on its way on Google Play, F-droid will follow shortly after :)
