### ISSUE TITLE
Update to Latest Version of KanjiVG

### ISSUE THREAD

**Issue by OkyDooky** [blastrock/kakugo#88]
Since the [last time I checked], KanjiVG has become active again on their Github and put out a [new release](https://github.com/KanjiVG/kanjivg/releases). I scanned through the commits from this year and couldn't see anything that resembled an upgrade to this component, but I am not very code-literate and may have missed it.
Hopefully this will fix some issues for people and help improve this app, as well.

**Comment by blastrock** [comment]
Thanks for the heads up. I just released a new version with updated kanjidic, jmdict and kanjivg.
